/* Automatically generated by configure - do not modify! */
#ifndef FFMPEG_CONFIG_H
#define FFMPEG_CONFIG_H
#define FFMPEG_CONFIGURATION ""
#define FFMPEG_VERSION "1.2.6"
#define FFMPEG_LICENSE "LGPL version 2.1 or later"
#define CC_IDENT "gcc 4.8.3 (Gentoo 4.8.3 p1.1, pie-0.5.9)"
#define CONFIG_AVCODEC 1
#define CONFIG_AVDEVICE 1
#define CONFIG_AVFORMAT 1
#define CONFIG_AVUTIL 1
#define CONFIG_SWRESAMPLE 1
#define CONFIG_SWSCALE 1
#define HAVE_SDL_VIDEO_SIZE 1
#endif /* FFMPEG_CONFIG_H */
